### ISSUE TITLE
如何保持自动登陆

### ISSUE THREAD

**Issue by esap** [OneWayTech/Vue-Auth-Solution#1]
RT,如果不用cookie或sessionStorge等本地持久化，怎样才防止用户下次访问又需要登陆。

**Comment by kenberkeley** [comment]
cookie 不需要前端操作，后端自行操作

**Comment by kenberkeley** [comment]
Nginx 设置一下动静分离就好了

**Comment by esap** [comment]
嗯，那其实还是需要一些cookie或localStorge存储token的吧

**Comment by kenberkeley** [comment]
登录凭证有很多方式，看你喜欢什么方式

**Comment by kenberkeley** [comment]
本方式比 Vuex 轻量，且支持双向绑定

**Comment by esap** [comment]
感谢解答，vuex确实有点太理论化了，我也喜欢用toolBus解决一些全局变量和方法

**Comment by kenberkeley** [comment]
在我的项目中，eventbus 有私有与全局之分，这样还可以避免命名空间的问题
